// AUTO-GENERATED by scripts/build-galleries.py — do not edit by hand.
// Per-product photo galleries + material groups from the client assets.

export interface GalleryGroup {
  material: string;
  label: string;
  icon: string | null; // /icons/materials/<key>.webp
  images: string[];
}
export interface ProductGallery {
  groups: GalleryGroup[];
  count: number;
}

export const MATERIAL_ICONS: Record<string, string> = {
  "wooden": "/icons/materials/wooden.webp",
  "brass": "/icons/materials/brass.webp",
  "silver": "/icons/materials/silver.webp",
  "copper": "/icons/materials/copper.webp",
  "diamond": "/icons/materials/diamond.webp",
  "minakari": "/icons/materials/minakari.webp",
  "polish": "/icons/materials/polish.webp",
  "inlay": "/icons/materials/inlay.webp",
  "brass-jaali": "/icons/materials/brass-jaali.webp",
  "copper-brass": "/icons/materials/copper-brass.webp",
  "brass-germansilver": "/icons/materials/brass-germansilver.webp"
};

export const GALLERIES: Record<string, ProductGallery> = {
  "14-swapna-and-parna": {
    "groups": [
      {
        "material": "diamond",
        "label": "Diamond",
        "icon": "diamond",
        "images": [
          "/gallery/14-swapna-and-parna/diamond/00.webp",
          "/gallery/14-swapna-and-parna/diamond/01.webp",
          "/gallery/14-swapna-and-parna/diamond/02.webp",
          "/gallery/14-swapna-and-parna/diamond/03.webp",
          "/gallery/14-swapna-and-parna/diamond/04.webp",
          "/gallery/14-swapna-and-parna/diamond/05.webp",
          "/gallery/14-swapna-and-parna/diamond/06.webp",
          "/gallery/14-swapna-and-parna/diamond/07.webp",
          "/gallery/14-swapna-and-parna/diamond/08.webp",
          "/gallery/14-swapna-and-parna/diamond/09.webp",
          "/gallery/14-swapna-and-parna/diamond/10.webp",
          "/gallery/14-swapna-and-parna/diamond/11.webp",
          "/gallery/14-swapna-and-parna/diamond/12.webp",
          "/gallery/14-swapna-and-parna/diamond/13.webp",
          "/gallery/14-swapna-and-parna/diamond/14.webp",
          "/gallery/14-swapna-and-parna/diamond/15.webp"
        ]
      },
      {
        "material": "minakari",
        "label": "Minakari",
        "icon": "minakari",
        "images": [
          "/gallery/14-swapna-and-parna/minakari/00.webp",
          "/gallery/14-swapna-and-parna/minakari/01.webp",
          "/gallery/14-swapna-and-parna/minakari/02.webp",
          "/gallery/14-swapna-and-parna/minakari/03.webp",
          "/gallery/14-swapna-and-parna/minakari/04.webp",
          "/gallery/14-swapna-and-parna/minakari/05.webp",
          "/gallery/14-swapna-and-parna/minakari/06.webp",
          "/gallery/14-swapna-and-parna/minakari/07.webp",
          "/gallery/14-swapna-and-parna/minakari/08.webp",
          "/gallery/14-swapna-and-parna/minakari/09.webp",
          "/gallery/14-swapna-and-parna/minakari/10.webp",
          "/gallery/14-swapna-and-parna/minakari/11.webp",
          "/gallery/14-swapna-and-parna/minakari/12.webp",
          "/gallery/14-swapna-and-parna/minakari/13.webp",
          "/gallery/14-swapna-and-parna/minakari/14.webp",
          "/gallery/14-swapna-and-parna/minakari/15.webp",
          "/gallery/14-swapna-and-parna/minakari/16.webp",
          "/gallery/14-swapna-and-parna/minakari/17.webp"
        ]
      },
      {
        "material": "polish",
        "label": "Polish",
        "icon": "polish",
        "images": [
          "/gallery/14-swapna-and-parna/polish/00.webp",
          "/gallery/14-swapna-and-parna/polish/01.webp",
          "/gallery/14-swapna-and-parna/polish/02.webp",
          "/gallery/14-swapna-and-parna/polish/03.webp",
          "/gallery/14-swapna-and-parna/polish/04.webp",
          "/gallery/14-swapna-and-parna/polish/05.webp",
          "/gallery/14-swapna-and-parna/polish/06.webp",
          "/gallery/14-swapna-and-parna/polish/07.webp",
          "/gallery/14-swapna-and-parna/polish/08.webp",
          "/gallery/14-swapna-and-parna/polish/09.webp",
          "/gallery/14-swapna-and-parna/polish/10.webp",
          "/gallery/14-swapna-and-parna/polish/11.webp",
          "/gallery/14-swapna-and-parna/polish/12.webp",
          "/gallery/14-swapna-and-parna/polish/13.webp",
          "/gallery/14-swapna-and-parna/polish/14.webp",
          "/gallery/14-swapna-and-parna/polish/15.webp"
        ]
      }
    ],
    "count": 50
  },
  "aluminium-platform-railing-and-ladder": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/aluminium-platform-railing-and-ladder/all/00.webp",
          "/gallery/aluminium-platform-railing-and-ladder/all/01.webp",
          "/gallery/aluminium-platform-railing-and-ladder/all/02.webp",
          "/gallery/aluminium-platform-railing-and-ladder/all/03.webp",
          "/gallery/aluminium-platform-railing-and-ladder/all/04.webp",
          "/gallery/aluminium-platform-railing-and-ladder/all/05.webp",
          "/gallery/aluminium-platform-railing-and-ladder/all/06.webp",
          "/gallery/aluminium-platform-railing-and-ladder/all/07.webp",
          "/gallery/aluminium-platform-railing-and-ladder/all/08.webp"
        ]
      }
    ],
    "count": 9
  },
  "angi-mugat": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/angi-mugat/all/00.webp",
          "/gallery/angi-mugat/all/01.webp",
          "/gallery/angi-mugat/all/02.webp",
          "/gallery/angi-mugat/all/03.webp",
          "/gallery/angi-mugat/all/04.webp",
          "/gallery/angi-mugat/all/05.webp",
          "/gallery/angi-mugat/all/06.webp",
          "/gallery/angi-mugat/all/07.webp",
          "/gallery/angi-mugat/all/08.webp",
          "/gallery/angi-mugat/all/09.webp",
          "/gallery/angi-mugat/all/10.webp",
          "/gallery/angi-mugat/all/11.webp",
          "/gallery/angi-mugat/all/12.webp",
          "/gallery/angi-mugat/all/13.webp",
          "/gallery/angi-mugat/all/14.webp"
        ]
      }
    ],
    "count": 15
  },
  "ashtaprakari-puja-bajot": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/ashtaprakari-puja-bajot/all/00.webp",
          "/gallery/ashtaprakari-puja-bajot/all/01.webp",
          "/gallery/ashtaprakari-puja-bajot/all/02.webp",
          "/gallery/ashtaprakari-puja-bajot/all/03.webp",
          "/gallery/ashtaprakari-puja-bajot/all/04.webp",
          "/gallery/ashtaprakari-puja-bajot/all/05.webp",
          "/gallery/ashtaprakari-puja-bajot/all/06.webp",
          "/gallery/ashtaprakari-puja-bajot/all/07.webp"
        ]
      }
    ],
    "count": 8
  },
  "bhandar": {
    "groups": [
      {
        "material": "brass-copper-bhandar",
        "label": "Brass Copper",
        "icon": "copper-brass",
        "images": [
          "/gallery/bhandar/brass-copper-bhandar/00.webp",
          "/gallery/bhandar/brass-copper-bhandar/01.webp",
          "/gallery/bhandar/brass-copper-bhandar/02.webp",
          "/gallery/bhandar/brass-copper-bhandar/03.webp",
          "/gallery/bhandar/brass-copper-bhandar/04.webp",
          "/gallery/bhandar/brass-copper-bhandar/05.webp",
          "/gallery/bhandar/brass-copper-bhandar/06.webp",
          "/gallery/bhandar/brass-copper-bhandar/07.webp",
          "/gallery/bhandar/brass-copper-bhandar/08.webp",
          "/gallery/bhandar/brass-copper-bhandar/09.webp"
        ]
      },
      {
        "material": "brass-jaali",
        "label": "Brass Jaali",
        "icon": "brass-jaali",
        "images": [
          "/gallery/bhandar/brass-jaali/00.webp"
        ]
      },
      {
        "material": "inlay",
        "label": "Inlay",
        "icon": "inlay",
        "images": [
          "/gallery/bhandar/inlay/00.webp"
        ]
      },
      {
        "material": "patra",
        "label": "Patra (Metal-clad)",
        "icon": null,
        "images": [
          "/gallery/bhandar/patra/00.webp",
          "/gallery/bhandar/patra/01.webp",
          "/gallery/bhandar/patra/02.webp",
          "/gallery/bhandar/patra/03.webp",
          "/gallery/bhandar/patra/04.webp",
          "/gallery/bhandar/patra/05.webp",
          "/gallery/bhandar/patra/06.webp",
          "/gallery/bhandar/patra/07.webp",
          "/gallery/bhandar/patra/08.webp",
          "/gallery/bhandar/patra/09.webp",
          "/gallery/bhandar/patra/10.webp",
          "/gallery/bhandar/patra/11.webp",
          "/gallery/bhandar/patra/12.webp",
          "/gallery/bhandar/patra/13.webp",
          "/gallery/bhandar/patra/14.webp",
          "/gallery/bhandar/patra/15.webp"
        ]
      }
    ],
    "count": 28
  },
  "brass-bell": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/brass-bell/all/00.webp",
          "/gallery/brass-bell/all/01.webp",
          "/gallery/brass-bell/all/02.webp",
          "/gallery/brass-bell/all/03.webp",
          "/gallery/brass-bell/all/04.webp",
          "/gallery/brass-bell/all/05.webp",
          "/gallery/brass-bell/all/06.webp"
        ]
      }
    ],
    "count": 7
  },
  "brass-gate": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/brass-gate/all/00.webp",
          "/gallery/brass-gate/all/01.webp",
          "/gallery/brass-gate/all/02.webp",
          "/gallery/brass-gate/all/03.webp",
          "/gallery/brass-gate/all/04.webp",
          "/gallery/brass-gate/all/05.webp",
          "/gallery/brass-gate/all/06.webp"
        ]
      }
    ],
    "count": 7
  },
  "brass-grill-jali": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/brass-grill-jali/all/00.webp",
          "/gallery/brass-grill-jali/all/01.webp",
          "/gallery/brass-grill-jali/all/02.webp",
          "/gallery/brass-grill-jali/all/03.webp",
          "/gallery/brass-grill-jali/all/04.webp",
          "/gallery/brass-grill-jali/all/05.webp",
          "/gallery/brass-grill-jali/all/06.webp",
          "/gallery/brass-grill-jali/all/07.webp",
          "/gallery/brass-grill-jali/all/08.webp",
          "/gallery/brass-grill-jali/all/09.webp"
        ]
      }
    ],
    "count": 10
  },
  "brass-tijori": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/brass-tijori/all/00.webp"
        ]
      }
    ],
    "count": 1
  },
  "chattar": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/chattar/all/00.webp",
          "/gallery/chattar/all/01.webp",
          "/gallery/chattar/all/02.webp",
          "/gallery/chattar/all/03.webp",
          "/gallery/chattar/all/04.webp",
          "/gallery/chattar/all/05.webp"
        ]
      }
    ],
    "count": 6
  },
  "deri-window-and-door": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/deri-window-and-door/all/00.webp",
          "/gallery/deri-window-and-door/all/01.webp",
          "/gallery/deri-window-and-door/all/02.webp",
          "/gallery/deri-window-and-door/all/03.webp",
          "/gallery/deri-window-and-door/all/04.webp"
        ]
      }
    ],
    "count": 5
  },
  "dhwajadand": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/dhwajadand/all/00.webp",
          "/gallery/dhwajadand/all/01.webp",
          "/gallery/dhwajadand/all/02.webp",
          "/gallery/dhwajadand/all/03.webp",
          "/gallery/dhwajadand/all/04.webp",
          "/gallery/dhwajadand/all/05.webp",
          "/gallery/dhwajadand/all/06.webp",
          "/gallery/dhwajadand/all/07.webp",
          "/gallery/dhwajadand/all/08.webp",
          "/gallery/dhwajadand/all/09.webp",
          "/gallery/dhwajadand/all/10.webp"
        ]
      }
    ],
    "count": 11
  },
  "divistand": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/divistand/all/00.webp",
          "/gallery/divistand/all/01.webp",
          "/gallery/divistand/all/02.webp",
          "/gallery/divistand/all/03.webp",
          "/gallery/divistand/all/04.webp",
          "/gallery/divistand/all/05.webp"
        ]
      }
    ],
    "count": 6
  },
  "door-step": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/door-step/all/00.webp",
          "/gallery/door-step/all/01.webp",
          "/gallery/door-step/all/02.webp",
          "/gallery/door-step/all/03.webp"
        ]
      }
    ],
    "count": 4
  },
  "doors": {
    "groups": [
      {
        "material": "brass-emboss",
        "label": "Brass Emboss",
        "icon": "inlay",
        "images": [
          "/gallery/doors/brass-emboss/00.webp"
        ]
      },
      {
        "material": "deep-carving",
        "label": "Deep Carving",
        "icon": "wooden",
        "images": [
          "/gallery/doors/deep-carving/00.webp",
          "/gallery/doors/deep-carving/01.webp",
          "/gallery/doors/deep-carving/02.webp",
          "/gallery/doors/deep-carving/03.webp"
        ]
      },
      {
        "material": "diamond-door",
        "label": "Diamond",
        "icon": "diamond",
        "images": [
          "/gallery/doors/diamond-door/00.webp",
          "/gallery/doors/diamond-door/01.webp"
        ]
      },
      {
        "material": "extra-deep-carving",
        "label": "Extra Deep Carving",
        "icon": "wooden",
        "images": [
          "/gallery/doors/extra-deep-carving/00.webp"
        ]
      },
      {
        "material": "inlay-emboss-jaali",
        "label": "Inlay Emboss Jaali",
        "icon": "inlay",
        "images": [
          "/gallery/doors/inlay-emboss-jaali/00.webp",
          "/gallery/doors/inlay-emboss-jaali/01.webp",
          "/gallery/doors/inlay-emboss-jaali/02.webp",
          "/gallery/doors/inlay-emboss-jaali/03.webp"
        ]
      },
      {
        "material": "normal-carving",
        "label": "Normal Carving",
        "icon": "wooden",
        "images": [
          "/gallery/doors/normal-carving/00.webp",
          "/gallery/doors/normal-carving/01.webp",
          "/gallery/doors/normal-carving/02.webp"
        ]
      },
      {
        "material": "patra-doors",
        "label": "Patra (Metal-clad)",
        "icon": null,
        "images": [
          "/gallery/doors/patra-doors/00.webp",
          "/gallery/doors/patra-doors/01.webp",
          "/gallery/doors/patra-doors/02.webp",
          "/gallery/doors/patra-doors/03.webp",
          "/gallery/doors/patra-doors/04.webp",
          "/gallery/doors/patra-doors/05.webp",
          "/gallery/doors/patra-doors/06.webp",
          "/gallery/doors/patra-doors/07.webp",
          "/gallery/doors/patra-doors/08.webp"
        ]
      },
      {
        "material": "silver-door",
        "label": "Silver",
        "icon": "silver",
        "images": [
          "/gallery/doors/silver-door/00.webp",
          "/gallery/doors/silver-door/01.webp",
          "/gallery/doors/silver-door/02.webp"
        ]
      }
    ],
    "count": 27
  },
  "kalash": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/kalash/all/00.webp",
          "/gallery/kalash/all/01.webp",
          "/gallery/kalash/all/02.webp",
          "/gallery/kalash/all/03.webp",
          "/gallery/kalash/all/04.webp",
          "/gallery/kalash/all/05.webp",
          "/gallery/kalash/all/06.webp",
          "/gallery/kalash/all/07.webp"
        ]
      }
    ],
    "count": 8
  },
  "kalpavruksh-naan": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/kalpavruksh-naan/all/00.webp",
          "/gallery/kalpavruksh-naan/all/01.webp",
          "/gallery/kalpavruksh-naan/all/02.webp"
        ]
      }
    ],
    "count": 3
  },
  "kumbh-kalash": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/kumbh-kalash/all/00.webp",
          "/gallery/kumbh-kalash/all/01.webp",
          "/gallery/kumbh-kalash/all/02.webp",
          "/gallery/kumbh-kalash/all/03.webp",
          "/gallery/kumbh-kalash/all/04.webp"
        ]
      }
    ],
    "count": 5
  },
  "mandir": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/mandir/all/00.webp",
          "/gallery/mandir/all/01.webp",
          "/gallery/mandir/all/02.webp",
          "/gallery/mandir/all/03.webp",
          "/gallery/mandir/all/04.webp",
          "/gallery/mandir/all/05.webp",
          "/gallery/mandir/all/06.webp",
          "/gallery/mandir/all/07.webp"
        ]
      }
    ],
    "count": 8
  },
  "manekstambh-toran": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/manekstambh-toran/all/00.webp",
          "/gallery/manekstambh-toran/all/01.webp",
          "/gallery/manekstambh-toran/all/02.webp",
          "/gallery/manekstambh-toran/all/03.webp",
          "/gallery/manekstambh-toran/all/04.webp",
          "/gallery/manekstambh-toran/all/05.webp",
          "/gallery/manekstambh-toran/all/06.webp",
          "/gallery/manekstambh-toran/all/07.webp",
          "/gallery/manekstambh-toran/all/08.webp",
          "/gallery/manekstambh-toran/all/09.webp",
          "/gallery/manekstambh-toran/all/10.webp",
          "/gallery/manekstambh-toran/all/11.webp",
          "/gallery/manekstambh-toran/all/12.webp",
          "/gallery/manekstambh-toran/all/13.webp",
          "/gallery/manekstambh-toran/all/14.webp",
          "/gallery/manekstambh-toran/all/15.webp",
          "/gallery/manekstambh-toran/all/16.webp"
        ]
      }
    ],
    "count": 17
  },
  "pakshal-kalash": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/pakshal-kalash/all/00.webp",
          "/gallery/pakshal-kalash/all/01.webp",
          "/gallery/pakshal-kalash/all/02.webp",
          "/gallery/pakshal-kalash/all/03.webp",
          "/gallery/pakshal-kalash/all/04.webp"
        ]
      }
    ],
    "count": 5
  },
  "patla": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/patla/all/00.webp",
          "/gallery/patla/all/01.webp",
          "/gallery/patla/all/02.webp",
          "/gallery/patla/all/03.webp",
          "/gallery/patla/all/04.webp",
          "/gallery/patla/all/05.webp",
          "/gallery/patla/all/06.webp",
          "/gallery/patla/all/07.webp",
          "/gallery/patla/all/08.webp",
          "/gallery/patla/all/09.webp"
        ]
      }
    ],
    "count": 10
  },
  "pichwadi": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/pichwadi/all/00.webp",
          "/gallery/pichwadi/all/01.webp",
          "/gallery/pichwadi/all/02.webp",
          "/gallery/pichwadi/all/03.webp",
          "/gallery/pichwadi/all/04.webp",
          "/gallery/pichwadi/all/05.webp"
        ]
      }
    ],
    "count": 6
  },
  "puja-table": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/puja-table/all/00.webp",
          "/gallery/puja-table/all/01.webp",
          "/gallery/puja-table/all/02.webp",
          "/gallery/puja-table/all/03.webp",
          "/gallery/puja-table/all/04.webp",
          "/gallery/puja-table/all/05.webp",
          "/gallery/puja-table/all/06.webp"
        ]
      }
    ],
    "count": 7
  },
  "rath": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/rath/all/00.webp",
          "/gallery/rath/all/01.webp",
          "/gallery/rath/all/02.webp",
          "/gallery/rath/all/03.webp"
        ]
      }
    ],
    "count": 4
  },
  "samovasaran-trigadu": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/samovasaran-trigadu/all/00.webp",
          "/gallery/samovasaran-trigadu/all/01.webp",
          "/gallery/samovasaran-trigadu/all/02.webp",
          "/gallery/samovasaran-trigadu/all/03.webp",
          "/gallery/samovasaran-trigadu/all/04.webp",
          "/gallery/samovasaran-trigadu/all/05.webp",
          "/gallery/samovasaran-trigadu/all/06.webp",
          "/gallery/samovasaran-trigadu/all/07.webp",
          "/gallery/samovasaran-trigadu/all/08.webp",
          "/gallery/samovasaran-trigadu/all/09.webp",
          "/gallery/samovasaran-trigadu/all/10.webp",
          "/gallery/samovasaran-trigadu/all/11.webp",
          "/gallery/samovasaran-trigadu/all/12.webp",
          "/gallery/samovasaran-trigadu/all/13.webp",
          "/gallery/samovasaran-trigadu/all/14.webp"
        ]
      }
    ],
    "count": 15
  },
  "shatrunjay-pat": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/shatrunjay-pat/all/00.webp",
          "/gallery/shatrunjay-pat/all/01.webp",
          "/gallery/shatrunjay-pat/all/02.webp",
          "/gallery/shatrunjay-pat/all/03.webp",
          "/gallery/shatrunjay-pat/all/04.webp",
          "/gallery/shatrunjay-pat/all/05.webp"
        ]
      }
    ],
    "count": 6
  },
  "silver-aarti-mangal-divo": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/silver-aarti-mangal-divo/all/00.webp",
          "/gallery/silver-aarti-mangal-divo/all/01.webp",
          "/gallery/silver-aarti-mangal-divo/all/02.webp",
          "/gallery/silver-aarti-mangal-divo/all/03.webp",
          "/gallery/silver-aarti-mangal-divo/all/04.webp",
          "/gallery/silver-aarti-mangal-divo/all/05.webp",
          "/gallery/silver-aarti-mangal-divo/all/06.webp",
          "/gallery/silver-aarti-mangal-divo/all/07.webp",
          "/gallery/silver-aarti-mangal-divo/all/08.webp"
        ]
      }
    ],
    "count": 9
  },
  "silver-kothi": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/silver-kothi/all/00.webp",
          "/gallery/silver-kothi/all/01.webp",
          "/gallery/silver-kothi/all/02.webp",
          "/gallery/silver-kothi/all/03.webp"
        ]
      }
    ],
    "count": 4
  },
  "sinhasan": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/sinhasan/all/00.webp",
          "/gallery/sinhasan/all/01.webp",
          "/gallery/sinhasan/all/02.webp",
          "/gallery/sinhasan/all/03.webp"
        ]
      }
    ],
    "count": 4
  },
  "vyaakhyan-kamal": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/vyaakhyan-kamal/all/00.webp",
          "/gallery/vyaakhyan-kamal/all/01.webp",
          "/gallery/vyaakhyan-kamal/all/02.webp",
          "/gallery/vyaakhyan-kamal/all/03.webp",
          "/gallery/vyaakhyan-kamal/all/04.webp"
        ]
      }
    ],
    "count": 5
  },
  "vyaakhyan-paat": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/vyaakhyan-paat/all/00.webp",
          "/gallery/vyaakhyan-paat/all/01.webp",
          "/gallery/vyaakhyan-paat/all/02.webp",
          "/gallery/vyaakhyan-paat/all/03.webp",
          "/gallery/vyaakhyan-paat/all/04.webp",
          "/gallery/vyaakhyan-paat/all/05.webp"
        ]
      }
    ],
    "count": 6
  },
  "wooden-carved-murti": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          "/gallery/wooden-carved-murti/all/00.webp"
        ]
      }
    ],
    "count": 1
  }
};

export function galleryFor(slug: string): ProductGallery | undefined {
  return GALLERIES[slug];
}
