// AUTO-GENERATED by scripts/build-galleries.py — do not edit by hand.
// Per-product photo galleries + material groups from the client assets.
// Later additions merged in by scripts/import-new-assets.py (additive;
// see that file for why the full rebuild is unsafe against this drop).

export interface GalleryImage {
  src: string;
  w: number;
  h: number; // intrinsic size (for exact-fit frames)
}
export interface GalleryGroup {
  material: string;
  label: string;
  icon: string | null; // /icons/materials/<key>.webp
  images: GalleryImage[];
}
export interface ProductGallery {
  groups: GalleryGroup[];
  count: number;
}

export const MATERIAL_ICONS: Record<string, string> = {
  "wooden": "/icons/materials/wooden.webp",
  "brass": "/icons/materials/brass.webp",
  "silver": "/icons/materials/silver.webp",
  "copper": "/icons/materials/copper.webp",
  "diamond": "/icons/materials/diamond.webp",
  "minakari": "/icons/materials/minakari.webp",
  "polish": "/icons/materials/polish.webp",
  "inlay": "/icons/materials/inlay.webp",
  "brass-jaali": "/icons/materials/brass-jaali.webp",
  "copper-brass": "/icons/materials/copper-brass.webp",
  "brass-germansilver": "/icons/materials/brass-germansilver.webp"
};

/** Every catalogue finish label -> its coin icon key (null = no coin).
  * Resolved by match_icon() in build-galleries.py so the client never
  * re-implements it. */
export const VARIANT_ICONS: Record<string, string | null> = {
  "Acrylic": null,
  "Brass": "brass",
  "Brass Jali": "brass-jaali",
  "Copper": "copper",
  "Copper + Brass": "copper-brass",
  "Diamond": "diamond",
  "GS + Brass": "brass-germansilver",
  "German Silver": "silver",
  "Gold": null,
  "Inlay": "inlay",
  "Inlay / Embossed": "inlay",
  "Jadtar (Full)": null,
  "Jadtar (Half)": null,
  "Minakari": "minakari",
  "Moti": null,
  "No-wood Metal": null,
  "Painting": null,
  "Silver": "silver",
  "Two-tone Polish": "polish",
  "Wire": null,
  "Wooden": "wooden"
};

export const GALLERIES: Record<string, ProductGallery> = {
  "108-diva-aarti": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/108-diva-aarti/all/00.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/108-diva-aarti/all/01.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 2
  },
  "14-swapna-and-parna": {
    "groups": [
      {
        "material": "diamond",
        "label": "Diamond",
        "icon": "diamond",
        "images": [
          {
            "src": "/gallery/14-swapna-and-parna/diamond/00.webp",
            "w": 1254,
            "h": 1254
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/01.webp",
            "w": 1254,
            "h": 1254
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/02.webp",
            "w": 1254,
            "h": 1254
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/03.webp",
            "w": 1254,
            "h": 1254
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/04.webp",
            "w": 1254,
            "h": 1254
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/05.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/06.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/07.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/08.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/09.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/10.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/11.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/12.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/13.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/14.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/diamond/15.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      },
      {
        "material": "minakari",
        "label": "Minakari",
        "icon": "minakari",
        "images": [
          {
            "src": "/gallery/14-swapna-and-parna/minakari/00.webp",
            "w": 1086,
            "h": 1448
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/01.webp",
            "w": 1086,
            "h": 1448
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/03.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/04.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/05.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/06.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/07.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/08.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/09.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/10.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/11.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/12.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/13.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/14.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/15.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/16.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/14-swapna-and-parna/minakari/17.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      },
      {
        "material": "polish",
        "label": "Polish",
        "icon": "polish",
        "images": [
          {
            "src": "/gallery/14-swapna-and-parna/polish/00.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/01.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/02.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/03.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/04.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/05.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/06.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/07.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/08.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/09.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/10.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/11.webp",
            "w": 1280,
            "h": 956
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/12.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/13.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/14.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/14-swapna-and-parna/polish/15.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 50
  },
  "aluminium-platform-railing-and-ladder": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/00.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/01.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/02.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/03.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/04.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/05.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/06.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/07.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/aluminium-platform-railing-and-ladder/all/08.webp",
            "w": 1448,
            "h": 1086
          }
        ]
      }
    ],
    "count": 9
  },
  "angi-mugat": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/angi-mugat/all/00.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/01.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/03.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/04.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/05.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/06.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/07.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/08.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/09.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/10.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/11.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/12.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/13.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/angi-mugat/all/14.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      }
    ],
    "count": 15
  },
  "ashtamangal": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/ashtamangal/all/00.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/ashtamangal/all/01.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/ashtamangal/all/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/ashtamangal/all/03.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/ashtamangal/all/04.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/ashtamangal/all/05.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/ashtamangal/all/06.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/ashtamangal/all/07.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/ashtamangal/all/08.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      }
    ],
    "count": 9
  },
  "ashtaprakari-puja-bajot": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/ashtaprakari-puja-bajot/all/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/ashtaprakari-puja-bajot/all/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/ashtaprakari-puja-bajot/all/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/ashtaprakari-puja-bajot/all/03.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/ashtaprakari-puja-bajot/all/04.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/ashtaprakari-puja-bajot/all/05.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/ashtaprakari-puja-bajot/all/06.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/ashtaprakari-puja-bajot/all/07.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 8
  },
  "bhandar": {
    "groups": [
      {
        "material": "brass-copper-bhandar",
        "label": "Brass Copper",
        "icon": "copper-brass",
        "images": [
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/00.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/01.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/02.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/03.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/04.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/05.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/06.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/07.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/08.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/bhandar/brass-copper-bhandar/09.webp",
            "w": 1448,
            "h": 1086
          }
        ]
      },
      {
        "material": "brass-jaali",
        "label": "Brass Jaali",
        "icon": "brass-jaali",
        "images": [
          {
            "src": "/gallery/bhandar/brass-jaali/00.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      },
      {
        "material": "inlay",
        "label": "Inlay",
        "icon": "inlay",
        "images": [
          {
            "src": "/gallery/bhandar/inlay/00.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      },
      {
        "material": "patra",
        "label": "Patra (Metal-clad)",
        "icon": null,
        "images": [
          {
            "src": "/gallery/bhandar/patra/00.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/01.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/03.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/04.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/05.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/06.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/07.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/08.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/09.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/10.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/11.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/12.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/13.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/14.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/bhandar/patra/15.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      }
    ],
    "count": 28
  },
  "brass-bell": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/brass-bell/all/00.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-bell/all/01.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-bell/all/02.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-bell/all/03.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-bell/all/04.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-bell/all/05.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-bell/all/06.webp",
            "w": 1448,
            "h": 1086
          }
        ]
      }
    ],
    "count": 7
  },
  "brass-bracket-and-chain": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/brass-bracket-and-chain/all/00.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-bracket-and-chain/all/01.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-bracket-and-chain/all/02.webp",
            "w": 1448,
            "h": 1086
          }
        ]
      }
    ],
    "count": 3
  },
  "brass-gate": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/brass-gate/all/00.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-gate/all/01.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-gate/all/02.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-gate/all/03.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-gate/all/04.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-gate/all/05.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-gate/all/06.webp",
            "w": 900,
            "h": 1600
          }
        ]
      }
    ],
    "count": 7
  },
  "brass-grill-jali": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/brass-grill-jali/all/00.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-grill-jali/all/01.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-grill-jali/all/02.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-grill-jali/all/03.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-grill-jali/all/04.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-grill-jali/all/05.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-grill-jali/all/06.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/brass-grill-jali/all/07.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/brass-grill-jali/all/08.webp",
            "w": 1451,
            "h": 1084
          },
          {
            "src": "/gallery/brass-grill-jali/all/09.webp",
            "w": 1200,
            "h": 1600
          }
        ]
      }
    ],
    "count": 10
  },
  "brass-tijori": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/brass-tijori/all/00.webp",
            "w": 900,
            "h": 1600
          }
        ]
      }
    ],
    "count": 1
  },
  "chattar": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/chattar/all/00.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/chattar/all/01.webp",
            "w": 1454,
            "h": 1082
          },
          {
            "src": "/gallery/chattar/all/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/chattar/all/03.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/chattar/all/04.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/chattar/all/05.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 6
  },
  "cloth-dhaja": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/cloth-dhaja/all/00.webp",
            "w": 365,
            "h": 1600
          },
          {
            "src": "/gallery/cloth-dhaja/all/01.webp",
            "w": 1600,
            "h": 1200
          },
          {
            "src": "/gallery/cloth-dhaja/all/02.webp",
            "w": 1200,
            "h": 1600
          },
          {
            "src": "/gallery/cloth-dhaja/all/03.webp",
            "w": 1600,
            "h": 1200
          }
        ]
      }
    ],
    "count": 4
  },
  "deri-window-and-door": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/deri-window-and-door/all/00.webp",
            "w": 1086,
            "h": 1449
          },
          {
            "src": "/gallery/deri-window-and-door/all/01.webp",
            "w": 1402,
            "h": 1122
          },
          {
            "src": "/gallery/deri-window-and-door/all/02.webp",
            "w": 1086,
            "h": 1448
          },
          {
            "src": "/gallery/deri-window-and-door/all/03.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/deri-window-and-door/all/04.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 5
  },
  "dhwajadand": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/dhwajadand/all/00.webp",
            "w": 1195,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/01.webp",
            "w": 1195,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/03.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/04.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/05.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/06.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/07.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/08.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/09.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/dhwajadand/all/10.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      }
    ],
    "count": 11
  },
  "divistand": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/divistand/all/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/divistand/all/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/divistand/all/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/divistand/all/03.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/divistand/all/04.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/divistand/all/05.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 6
  },
  "door-step": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/door-step/all/00.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/door-step/all/01.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/door-step/all/02.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/door-step/all/03.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 4
  },
  "doors": {
    "groups": [
      {
        "material": "brass-emboss",
        "label": "Brass Emboss",
        "icon": "inlay",
        "images": [
          {
            "src": "/gallery/doors/brass-emboss/00.webp",
            "w": 1195,
            "h": 1600
          }
        ]
      },
      {
        "material": "deep-carving",
        "label": "Deep Carving",
        "icon": "wooden",
        "images": [
          {
            "src": "/gallery/doors/deep-carving/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/deep-carving/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/deep-carving/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/deep-carving/03.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      },
      {
        "material": "diamond-door",
        "label": "Diamond",
        "icon": "diamond",
        "images": [
          {
            "src": "/gallery/doors/diamond-door/00.webp",
            "w": 1086,
            "h": 1448
          },
          {
            "src": "/gallery/doors/diamond-door/01.webp",
            "w": 893,
            "h": 1600
          }
        ]
      },
      {
        "material": "extra-deep-carving",
        "label": "Extra Deep Carving",
        "icon": "wooden",
        "images": [
          {
            "src": "/gallery/doors/extra-deep-carving/00.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      },
      {
        "material": "inlay-emboss-jaali",
        "label": "Inlay Emboss Jaali",
        "icon": "inlay",
        "images": [
          {
            "src": "/gallery/doors/inlay-emboss-jaali/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/inlay-emboss-jaali/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/inlay-emboss-jaali/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/inlay-emboss-jaali/03.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      },
      {
        "material": "normal-carving",
        "label": "Normal Carving",
        "icon": "wooden",
        "images": [
          {
            "src": "/gallery/doors/normal-carving/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/normal-carving/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/normal-carving/02.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      },
      {
        "material": "patra-doors",
        "label": "Patra (Metal-clad)",
        "icon": null,
        "images": [
          {
            "src": "/gallery/doors/patra-doors/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/patra-doors/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/patra-doors/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/patra-doors/03.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/patra-doors/04.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/patra-doors/05.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/patra-doors/06.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/patra-doors/07.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/doors/patra-doors/08.webp",
            "w": 1195,
            "h": 1600
          }
        ]
      },
      {
        "material": "silver-door",
        "label": "Silver",
        "icon": "silver",
        "images": [
          {
            "src": "/gallery/doors/silver-door/00.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/doors/silver-door/01.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/doors/silver-door/02.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 27
  },
  "kalash": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/kalash/all/00.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kalash/all/01.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kalash/all/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kalash/all/03.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kalash/all/04.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kalash/all/05.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kalash/all/06.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kalash/all/07.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      }
    ],
    "count": 8
  },
  "kalpavruksh-naan": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/kalpavruksh-naan/all/00.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/kalpavruksh-naan/all/01.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/kalpavruksh-naan/all/02.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 3
  },
  "kumbh-kalash": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/kumbh-kalash/all/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/kumbh-kalash/all/01.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kumbh-kalash/all/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/kumbh-kalash/all/03.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/kumbh-kalash/all/04.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 5
  },
  "mandir": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/mandir/all/00.webp",
            "w": 1086,
            "h": 1448
          },
          {
            "src": "/gallery/mandir/all/01.webp",
            "w": 1334,
            "h": 1179
          },
          {
            "src": "/gallery/mandir/all/02.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/mandir/all/03.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/mandir/all/04.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/mandir/all/05.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/mandir/all/06.webp",
            "w": 1448,
            "h": 1086
          },
          {
            "src": "/gallery/mandir/all/07.webp",
            "w": 1086,
            "h": 1448
          }
        ]
      }
    ],
    "count": 8
  },
  "manekstambh-toran": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/manekstambh-toran/all/00.webp",
            "w": 1082,
            "h": 1453
          },
          {
            "src": "/gallery/manekstambh-toran/all/01.webp",
            "w": 1122,
            "h": 1402
          },
          {
            "src": "/gallery/manekstambh-toran/all/02.webp",
            "w": 1122,
            "h": 1402
          },
          {
            "src": "/gallery/manekstambh-toran/all/03.webp",
            "w": 1114,
            "h": 1411
          },
          {
            "src": "/gallery/manekstambh-toran/all/04.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/05.webp",
            "w": 1114,
            "h": 1412
          },
          {
            "src": "/gallery/manekstambh-toran/all/06.webp",
            "w": 1086,
            "h": 1449
          },
          {
            "src": "/gallery/manekstambh-toran/all/07.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/08.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/09.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/10.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/11.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/12.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/13.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/14.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/15.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/manekstambh-toran/all/16.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 17
  },
  "navkar-pat": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/navkar-pat/all/00.webp",
            "w": 1084,
            "h": 1451
          },
          {
            "src": "/gallery/navkar-pat/all/01.webp",
            "w": 1600,
            "h": 847
          }
        ]
      }
    ],
    "count": 2
  },
  "pakshal-kalash": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/pakshal-kalash/all/00.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/pakshal-kalash/all/01.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/pakshal-kalash/all/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/pakshal-kalash/all/03.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/pakshal-kalash/all/04.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      }
    ],
    "count": 5
  },
  "palkhi": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/palkhi/all/00.webp",
            "w": 900,
            "h": 1600
          }
        ]
      }
    ],
    "count": 1
  },
  "patla": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/patla/all/00.webp",
            "w": 1600,
            "h": 1243
          },
          {
            "src": "/gallery/patla/all/01.webp",
            "w": 1600,
            "h": 1296
          },
          {
            "src": "/gallery/patla/all/02.webp",
            "w": 1600,
            "h": 1228
          },
          {
            "src": "/gallery/patla/all/03.webp",
            "w": 1600,
            "h": 1388
          }
        ]
      }
    ],
    "count": 4
  },
  "pichwadi": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/pichwadi/all/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/pichwadi/all/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/pichwadi/all/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/pichwadi/all/03.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/pichwadi/all/04.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/pichwadi/all/05.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 6
  },
  "puja-table": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/puja-table/all/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/puja-table/all/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/puja-table/all/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/puja-table/all/03.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/puja-table/all/04.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/puja-table/all/05.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/puja-table/all/06.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 7
  },
  "rath": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/rath/all/00.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/rath/all/01.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/rath/all/02.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/rath/all/03.webp",
            "w": 900,
            "h": 1600
          }
        ]
      }
    ],
    "count": 4
  },
  "samovasaran-trigadu": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/samovasaran-trigadu/all/00.webp",
            "w": 900,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/01.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/02.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/03.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/04.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/05.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/06.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/07.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/08.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/09.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/10.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/11.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/12.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/13.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/samovasaran-trigadu/all/14.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 15
  },
  "shatrunjay-pat": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/shatrunjay-pat/all/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/shatrunjay-pat/all/01.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/shatrunjay-pat/all/02.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/shatrunjay-pat/all/03.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/shatrunjay-pat/all/04.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/shatrunjay-pat/all/05.webp",
            "w": 1600,
            "h": 1200
          }
        ]
      }
    ],
    "count": 6
  },
  "silver-aarti-mangal-divo": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/00.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/01.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/02.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/03.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/04.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/05.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/06.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/07.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-aarti-mangal-divo/all/08.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 9
  },
  "silver-chaamar": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/silver-chaamar/all/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/silver-chaamar/all/01.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 2
  },
  "silver-darpan": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/silver-darpan/all/00.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 1
  },
  "silver-frames": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/silver-frames/all/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/silver-frames/all/01.webp",
            "w": 1600,
            "h": 1085
          }
        ]
      }
    ],
    "count": 2
  },
  "silver-kothi": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/silver-kothi/all/00.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-kothi/all/01.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-kothi/all/02.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/silver-kothi/all/03.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 4
  },
  "silver-pankho": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/silver-pankho/all/00.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 1
  },
  "sinhasan": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/sinhasan/all/00.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/sinhasan/all/01.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/sinhasan/all/02.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/sinhasan/all/03.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 4
  },
  "table": {
    "groups": [
      {
        "material": "wooden",
        "label": "Wooden",
        "icon": "wooden",
        "images": [
          {
            "src": "/gallery/table/wooden/00.webp",
            "w": 1600,
            "h": 1195
          },
          {
            "src": "/gallery/table/wooden/01.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      },
      {
        "material": "german-silver",
        "label": "German Silver",
        "icon": "silver",
        "images": [
          {
            "src": "/gallery/table/german-silver/00.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      },
      {
        "material": "gs-brass",
        "label": "GS + Brass",
        "icon": "brass-germansilver",
        "images": [
          {
            "src": "/gallery/table/gs-brass/00.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 4
  },
  "toran": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/toran/all/00.webp",
            "w": 1600,
            "h": 539
          },
          {
            "src": "/gallery/toran/all/01.webp",
            "w": 1600,
            "h": 1200
          },
          {
            "src": "/gallery/toran/all/02.webp",
            "w": 1600,
            "h": 735
          },
          {
            "src": "/gallery/toran/all/03.webp",
            "w": 1600,
            "h": 309
          },
          {
            "src": "/gallery/toran/all/04.webp",
            "w": 1600,
            "h": 558
          },
          {
            "src": "/gallery/toran/all/05.webp",
            "w": 1600,
            "h": 1200
          },
          {
            "src": "/gallery/toran/all/06.webp",
            "w": 1600,
            "h": 1600
          },
          {
            "src": "/gallery/toran/all/07.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      }
    ],
    "count": 8
  },
  "vyaakhyan-kamal": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/vyaakhyan-kamal/all/00.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-kamal/all/01.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-kamal/all/02.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-kamal/all/03.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-kamal/all/04.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 5
  },
  "vyaakhyan-paat": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/vyaakhyan-paat/all/00.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-paat/all/01.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-paat/all/02.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-paat/all/03.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-paat/all/04.webp",
            "w": 893,
            "h": 1600
          },
          {
            "src": "/gallery/vyaakhyan-paat/all/05.webp",
            "w": 893,
            "h": 1600
          }
        ]
      }
    ],
    "count": 6
  },
  "wooden-carved-murti": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/wooden-carved-murti/all/00.webp",
            "w": 1600,
            "h": 1600
          }
        ]
      }
    ],
    "count": 1
  },
  "wooden-ceiling": {
    "groups": [
      {
        "material": "all",
        "label": "All",
        "icon": null,
        "images": [
          {
            "src": "/gallery/wooden-ceiling/all/00.webp",
            "w": 1600,
            "h": 1195
          }
        ]
      }
    ],
    "count": 1
  }
};

export function galleryFor(slug: string): ProductGallery | undefined {
  return GALLERIES[slug];
}
