#!/usr/bin/env python3
"""Additively import client photos into the gallery manifest.

WHY THIS EXISTS INSTEAD OF RE-RUNNING build-galleries.py
--------------------------------------------------------
build-galleries.py is a FULL REBUILD: it rmtree's public/gallery and re-derives
src/lib/galleries.ts from scratch. Against the current client drop that would
destroy work, for two reasons:

  1. The drop is a LATER one than the importer was written for. Two source
     folders it maps are simply gone ("Allumium Platform Railing ", "Deri
     Window "), but their encoded output is live on the site. A rebuild drops
     both products' galleries.
  2. The drop has NO "icon-buttons " folder. MATERIAL_ICONS is built from it, so
     a rebuild emits `{}` and every material coin on every piece page silently
     disappears.

So this script only ADDS. It reads the existing manifest, encodes the new files,
merges them in, and writes the manifest back with MATERIAL_ICONS and
VARIANT_ICONS carried through untouched. Nothing already on disk is deleted.

Input: a JSON plan on argv[1] —
    { "<slug>": { "groups": [ { "label": "All", "material": "all",
                                "files": ["<abs path>", ...] } ] } }

Run: /usr/bin/python3 scripts/import-new-assets.py plan.json
"""
import json, os, re, sys
from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_IMG = os.path.join(ROOT, "public", "gallery")
OUT_TS = os.path.join(ROOT, "src", "lib", "galleries.ts")
MAXPX, QUALITY = 1600, 82


def read_ts_object(src, name):
    """Pull one `export const <name>... = {...};` literal out of galleries.ts.

    The file is machine-written by build-galleries.py via json.dumps, so every
    one of these literals is strict JSON and can be parsed as such. Brace-match
    rather than regex — the values contain braces."""
    i = src.index(f"export const {name}")
    start = src.index("{", i)
    depth = 0
    for j in range(start, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                return json.loads(src[start : j + 1])
    raise ValueError(f"unterminated object for {name}")


def encode(src_path, dst):
    im = Image.open(src_path)
    im = ImageOps.exif_transpose(im).convert("RGB")
    im.thumbnail((MAXPX, MAXPX), Image.LANCZOS)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    im.save(dst, "WEBP", quality=QUALITY, method=6)
    return os.path.getsize(dst), im.size


def main():
    plan = json.load(open(sys.argv[1]))
    src = open(OUT_TS).read()
    icons = read_ts_object(src, "MATERIAL_ICONS")
    variant_icons = read_ts_object(src, "VARIANT_ICONS")
    manifest = read_ts_object(src, "GALLERIES")
    before = len(manifest)

    total_bytes = total_files = 0
    for slug, spec in sorted(plan.items()):
        groups = []
        for g in spec["groups"]:
            mslug = g["material"]
            images = []
            for i, f in enumerate(g["files"]):
                if not os.path.isfile(f):
                    print(f"  !! missing {f}", file=sys.stderr)
                    continue
                web = f"/gallery/{slug}/{mslug}/{i:02d}.webp"
                b, (w, h) = encode(f, os.path.join(OUT_IMG, slug, mslug, f"{i:02d}.webp"))
                total_bytes += b
                total_files += 1
                images.append({"src": web, "w": w, "h": h})
            if images:
                groups.append({
                    "material": mslug,
                    "label": g["label"],
                    "icon": g.get("icon"),
                    "images": images,
                })
        if not groups:
            continue
        # Merge, don't clobber: a product may already have material folders and
        # this plan may be adding one more.
        existing = manifest.get(slug)
        if existing:
            have = {x["material"] for x in existing["groups"]}
            existing["groups"] += [g for g in groups if g["material"] not in have]
            existing["count"] = sum(len(g["images"]) for g in existing["groups"])
            print(f"  + {slug:34s} merged -> {existing['count']} imgs, "
                  f"{len(existing['groups'])} group(s)")
        else:
            manifest[slug] = {
                "groups": groups,
                "count": sum(len(g["images"]) for g in groups),
            }
            print(f"  NEW {slug:34s} {manifest[slug]['count']:3d} imgs, "
                  f"{len(groups)} group(s): {[g['label'] for g in groups]}")

    manifest = dict(sorted(manifest.items()))
    header = (
        "// AUTO-GENERATED by scripts/build-galleries.py — do not edit by hand.\n"
        "// Per-product photo galleries + material groups from the client assets.\n"
        "// Later additions merged in by scripts/import-new-assets.py (additive;\n"
        "// see that file for why the full rebuild is unsafe against this drop).\n\n"
        "export interface GalleryImage {\n"
        "  src: string;\n  w: number;\n  h: number; // intrinsic size (for exact-fit frames)\n}\n"
        "export interface GalleryGroup {\n"
        "  material: string;\n  label: string;\n"
        "  icon: string | null; // /icons/materials/<key>.webp\n"
        "  images: GalleryImage[];\n}\n"
        "export interface ProductGallery {\n  groups: GalleryGroup[];\n  count: number;\n}\n\n"
        f"export const MATERIAL_ICONS: Record<string, string> = {json.dumps(icons, indent=2)};\n\n"
        "/** Every catalogue finish label -> its coin icon key (null = no coin).\n"
        "  * Resolved by match_icon() in build-galleries.py so the client never\n"
        "  * re-implements it. */\n"
        f"export const VARIANT_ICONS: Record<string, string | null> = {json.dumps(variant_icons, indent=2)};\n\n"
        f"export const GALLERIES: Record<string, ProductGallery> = {json.dumps(manifest, indent=2)};\n\n"
        "export function galleryFor(slug: string): ProductGallery | undefined {\n"
        "  return GALLERIES[slug];\n}\n"
    )
    open(OUT_TS, "w").write(header)
    print(f"\n{before} -> {len(manifest)} products, +{total_files} images, "
          f"{total_bytes/1e6:.1f} MB")
    print(f"carried through: {len(icons)} material icons, {len(variant_icons)} finish labels")
    print("wrote", OUT_TS)


if __name__ == "__main__":
    main()
